import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../cloud-auth.js',import.meta.url),'utf8');
const root={URL,atob,console};vm.runInNewContext(source,root);
const store=new Map(),events=[],requests=[];let now=1000000,responses=[];
const storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
const auth=root.MyfinCloudAuth.createClient({storage,now:()=>now,onChange:(s,r)=>events.push(r),fetch:async(url,opt)=>{requests.push({url,opt});const r=responses.shift();if(typeof r==='function')return r();return {ok:true,json:async()=>r};}});
const user='00000000-0000-4000-8000-000000000001';
const result=(id=user)=>({access_token:'ACCESS-'+id,refresh_token:'REFRESH',expires_in:3600,user:{id,email:'test@example.test'}});
assert.throws(()=>auth.configure('https://evil.test','sb_publishable_test'),/invalid-project/);
assert.throws(()=>auth.configure('https://one.supabase.co','sb_secret_admin'),/public-key/);
auth.configure('https://one.supabase.co','sb_publishable_test');
await assert.rejects(auth.token(),/login-required/);
responses=[result()];await auth.signIn('test@example.test','PRIVATE-PASSWORD');
assert.equal(auth.status().userId,user);assert.equal(await auth.token(),'ACCESS-'+user);
assert.equal(requests.length,1);assert.ok(requests.every(r=>r.url.includes('/auth/v1/')));
assert.ok(!JSON.stringify([...store]).includes('PRIVATE-PASSWORD'));
assert.ok(!JSON.stringify(auth.status()).includes('ACCESS-'));
assert.equal(requests[0].opt.redirect,'error');
now+=3550000;responses=[result()];const [a,b]=await Promise.all([auth.token(),auth.token()]);assert.equal(a,b);assert.equal(requests.length,2,'one refresh for concurrent callers');
let complete;now+=3550000;responses=[()=>new Promise(r=>{complete=r;})];const pending=auth.token();
responses.push({});await auth.signOut();complete({ok:true,json:async()=>result()});await assert.rejects(pending,/auth-cancelled/);
assert.equal(auth.status().userId,'');assert.equal(store.size,0);
responses=[result()];await auth.signIn('test@example.test','PRIVATE-PASSWORD');
auth.configure('https://two.supabase.co','sb_publishable_test');assert.equal(auth.status().userId,'');
auth.configure('https://one.supabase.co','sb_publishable_test');assert.equal(auth.status().userId,user);
now+=3550000;responses=[result('someone-else')];await assert.rejects(auth.token(),/invalid-session/);assert.equal(auth.status().userId,'');
responses=[{user:{id:user}}];assert.equal((await auth.signUp('test@example.test','P','https://example.test/Myfin/')).confirmationRequired,true);
assert.equal(auth.status().userId,'','registration does not auto-login');
assert.ok(requests.every(r=>!r.url.includes('/rest/v1/')),'auth never touches ledger');
responses=[result()];await auth.signIn('test@example.test','P');now+=3550000;
responses=[()=>({ok:false,status:401,json:async()=>({})})];await assert.rejects(auth.token(),/auth-failed/);assert.equal(auth.status().userId,'','401 during refresh clears the expired session');
const denied={URL,atob,console,fetch:async()=>({ok:true,json:async()=>result()})};Object.defineProperty(denied,'sessionStorage',{get(){throw Error('denied');}});vm.runInNewContext(source,denied);assert.doesNotThrow(()=>denied.MyfinCloudAuth.createClient(),'blocked sessionStorage does not crash local app');
console.log('Optional auth: isolation, no auto sync, refresh, logout race, safe storage passed.');
