import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
function fn(n){const s=html.indexOf('function '+n+'(');assert.ok(s>=0,n);const end=html.slice(s+10).search(/\n(?:async )?function /);return html.slice(s,s+10+end);}
function setup(apr=0){const now=new Date(),ym=now.getFullYear()*12+now.getMonth();const c={console,Date,Math,JSON,Number,setTimeout,clearTimeout,window:{_cloudEpoch:0},S:{debts:[{id:'d',name:'Test',cur:'HKD',acctId:'bank',balance:1000,principal0:1000,paidTotal:0,accInterest:0,apr,monthly:100,day:1,lastYM:ym-1,anchorYM:ym-1}],txns:[]},document:{getElementById:()=>null},profileKey:()=> 'a',getAcct:()=>({id:'bank'}),acctLabel:()=> 'bank',toHKD:n=>n,t:x=>x,tt:(a,b)=>b,dimM:(y,m)=>new Date(y,m+1,0).getDate(),saveS:()=>true,renderHome:()=>{},refreshWallet:()=>{},refreshAllViews:()=>{},renderDebts:()=>{},showToast:m=>c.message=m,confirm:()=>true};vm.createContext(c);vm.runInContext(['ymNum','debtMonthlyRate','checkDebts','debtRepaymentReversal','deleteTxn','undoDeleteTxn','deleteDebt','toggleTxnExclude'].filter(n=>html.includes('function '+n+'(')).map(fn).join('\n')+'\nfunction showUndoToast(){}',c);c.checkDebts();return c;}
test('delete and undo repayment keep debt and cash together',()=>{const c=setup();assert.equal(c.S.debts[0].balance,900);const id=c.S.txns[0].id;c.deleteTxn(id);assert.equal(c.S.debts[0].balance,1000);assert.equal(c.S.debts[0].paidTotal,0);assert.equal(c.S.txns.length,0);c.checkDebts();assert.equal(c.S.txns.length,0);c.undoDeleteTxn();assert.equal(c.S.debts[0].balance,900);assert.equal(c.S.debts[0].paidTotal,100);assert.equal(c.S.txns.length,1);});
test('reversal retains accrued interest rather than guessing principal',()=>{const c=setup(12);c.deleteTxn(c.S.txns[0].id);assert.equal(c.S.debts[0].balance,1010);assert.equal(c.S.debts[0].accInterest,10);c.undoDeleteTxn();assert.equal(c.S.debts[0].balance,910);});
test('legacy repayment without evidence cannot be deleted',()=>{const c=setup();delete c.S.txns[0].debtEffect;const before=JSON.stringify(c.S);c.deleteTxn(c.S.txns[0].id);assert.equal(JSON.stringify(c.S),before);});
test('subsequent debt changes block historical reversal',()=>{const c=setup();c.S.debts[0].balance+=10;const before=JSON.stringify(c.S);c.deleteTxn(c.S.txns[0].id);assert.equal(JSON.stringify(c.S),before);});
test('failed delete save restores both sides',()=>{const c=setup();const before=JSON.stringify(c.S);c.saveS=()=>false;c.deleteTxn(c.S.txns[0].id);assert.equal(JSON.stringify(c.S),before);});
test('failed undo save leaves deletion consistent and retryable',()=>{const c=setup();c.deleteTxn(c.S.txns[0].id);const before=JSON.stringify(c.S);c.saveS=()=>false;c.undoDeleteTxn();assert.equal(JSON.stringify(c.S),before);c.saveS=()=>true;c.undoDeleteTxn();assert.equal(c.S.debts[0].balance,900);});
test('undo cannot cross ledger boundary',()=>{const c=setup();c.deleteTxn(c.S.txns[0].id);c.S={debts:[],txns:[]};c.undoDeleteTxn();assert.equal(c.S.txns.length,0);});
test('linked repayment cannot be excluded or orphaned by deleting debt',()=>{const c=setup();const before=JSON.stringify(c.S);c.toggleTxnExclude(c.S.txns[0].id);assert.equal(JSON.stringify(c.S),before);c.deleteDebt('d');assert.equal(JSON.stringify(c.S),before);});
test('failed recurring payment save restores consumed period and both sides',()=>{const c=setup();c.S.debts[0].lastYM--;const before=JSON.stringify(c.S);c.saveS=()=>false;c.checkDebts();assert.equal(JSON.stringify(c.S),before);});
test('undo rejects subsequent debt changes without restoring cash alone',()=>{const c=setup();c.deleteTxn(c.S.txns[0].id);c.S.debts[0].balance+=10;const before=JSON.stringify(c.S);c.undoDeleteTxn();assert.equal(JSON.stringify(c.S),before);});
test('evidence survives JSON persistence and fractional final payment',()=>{const c=setup();c.S.debts[0].balance=5.123;c.S.debts[0].lastYM--;c.checkDebts();c.S=JSON.parse(JSON.stringify(c.S));const tx=c.S.txns[0];assert.equal(c.S.debts[0].balance,0);c.deleteTxn(tx.id);assert.equal(c.S.debts[0].balance,5.123);c.undoDeleteTxn();assert.equal(c.S.debts[0].balance,0);});
test('corrupt evidence cannot reset unrelated terms',()=>{const c=setup();c.S.txns[0].debtEffect.before.apr=99;const before=JSON.stringify(c.S);c.deleteTxn(c.S.txns[0].id);assert.equal(JSON.stringify(c.S),before);});
test('linked opening cannot be removed as a normal transaction',()=>{const c=setup();c.S.txns.unshift({id:'open',type:'debt_move',debtId:'d',debtPhase:'open',amount:1000});const before=JSON.stringify(c.S);c.deleteTxn('open');assert.equal(JSON.stringify(c.S),before);});
test('ordinary transaction deletion and undo still work without changing debt',()=>{const c=setup();c.S.txns.push({id:'ordinary',type:'expense',amount:5});const before=JSON.stringify(c.S);c.deleteTxn('ordinary');assert.equal(c.S.txns.length,1);c.undoDeleteTxn();assert.equal(JSON.stringify(c.S),before);});
test('linked entries are blocked at both editor entry and save boundary',()=>{const c=setup();vm.runInContext(fn('editTxn')+'\n'+fn('saveTxn'),c);const tx=c.S.txns[0];c.editTxn(tx.id);assert.equal(c.S._editTxnId,undefined);c.S._editTxnId=tx.id;const before=JSON.stringify(c.S);c.saveTxn();assert.equal(JSON.stringify(c.S),before);});
