import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
function fn(name){const start=html.search(new RegExp('(?:async )?function '+name+'\\('));assert.ok(start>=0,name);const tail=html.slice(start);const end=tail.slice(10).search(/\n(?:async )?function /);return end<0?tail:tail.slice(0,end+10);}
function setup(){
  const c={console,Date,Number,Math,JSON,Set,FX:{USD:8,RMB:1.1,JPY:.05},S:{fx:{USD:8,RMB:1.1,JPY:.05,updated:123},portfolio:[],physicalAssets:[]},document:{querySelectorAll:()=>[],getElementById:()=>null},window:{_cloudEpoch:0},profileKey:()=> 'a',tt:(a,b)=>b,t:k=>k,setPriceStatus:(s,m)=>{c.status={s,m};},fetch:async()=>{throw Error('offline');},fetchCoinGeckoPrices:async()=>({}),cgId:n=>n==='BTC'?'bitcoin':null,hasQuoteKey:()=>false,fetchTwelveDataPrice:async()=>42,refreshTrackedMetalPrices:async()=>true,toHKD:(n,cur)=>n*(c.FX[cur]||1),recordPriceSnapshot:()=>c.snapshots++,saveS:()=>true,refreshAllViews:()=>{},renderFxRates:()=>{},snapshots:0};
  vm.createContext(c);vm.runInContext('let _refreshing=false;'+['priceRefreshLabel','refreshPrices','maybeAutoRefresh'].filter(n=>html.includes('function '+n+'(')).map(fn).join('\n'),c);return c;
}
test('empty holdings plus offline FX is failure, not success or fresh rates',async()=>{const c=setup();await c.refreshPrices(false);assert.equal(c.status.s,'err');assert.equal(c.S.fx.updated,123);assert.equal(c.snapshots,0);});
test('malformed FX response cannot mark old rates fresh',async()=>{const c=setup();c.fetch=async()=>({ok:true,json:async()=>({rates:{USD:0,CNY:-1,JPY:'bad'}})});await c.refreshPrices();assert.equal(c.S.fx.updated,123);assert.equal(c.FX.USD,8);assert.equal(c.status.s,'err');});
test('missing stock key and unsupported crypto are failures, not skipped successes',async()=>{const c=setup();c.S.portfolio=[{type:'stock',name:'ABC',qty:1,cur:'USD',currentPrice:20},{type:'crypto',name:'unknown',qty:1,cur:'USD',currentPrice:10}];await c.refreshPrices();assert.equal(c.status.s,'err');assert.equal(c.S.portfolio[0].currentPrice,20);});
test('partial crypto payload reports missing item and preserves cached quote/currency',async()=>{const c=setup();c.S.portfolio=[{type:'crypto',name:'BTC',qty:1,cur:'USD',currentPrice:20},{type:'crypto',name:'unknown',qty:1,cur:'USD',currentPrice:10}];c.fetchCoinGeckoPrices=async()=>({bitcoin:{hkd:800}});await c.refreshPrices();assert.equal(c.S.portfolio[0].currentPrice,100);assert.equal(c.S.portfolio[0].cur,'USD');assert.equal(c.status.s,'err');assert.match(c.status.m,/Partial/);assert.equal(c.S.fx.updated,123);});
test('valid FX-only update succeeds and survives status reconstruction',async()=>{const c=setup();c.fetch=async()=>({ok:true,json:async()=>({rates:{USD:.125,CNY:1,JPY:20}})});await c.refreshPrices();assert.equal(c.status.s,'ok');assert.ok(c.S.fx.updated>123);assert.equal(c.S.fx.quoteRefresh.sources.stock.total,0);});
test('profile switch while FX request is pending discards old response',async()=>{const c=setup();let resolve;c.fetch=()=>new Promise(r=>resolve=r);const running=c.refreshPrices();c.S={fx:{updated:456},portfolio:[]};resolve({ok:true,json:async()=>({rates:{USD:.1,CNY:1,JPY:20}})});await running;assert.equal(c.S.fx.updated,456);assert.equal(c.FX.USD,8);assert.equal(c.snapshots,0);});
test('failed refresh retries after short cooldown, not 24 hours',async()=>{const c=setup();await c.refreshPrices();c.S.fx.quoteRefresh.attemptedAt=Date.now()-6*60*1000;let calls=0;c.refreshPrices=()=>calls++;c.maybeAutoRefresh();assert.equal(calls,1);});
test('partial stocks count actual valid prices, not configured keys',async()=>{const c=setup();c.hasQuoteKey=()=>true;c.S.portfolio=['A','B'].map(name=>({type:'stock',name,cur:'USD',qty:1,currentPrice:20}));c.fetchTwelveDataPrice=async name=>name==='A'?30:NaN;await c.refreshPrices();assert.equal(c.S.fx.quoteRefresh.sources.stock.ok,1);assert.equal(c.S.portfolio[1].currentPrice,20);assert.match(c.status.m,/Stocks 1\/2/);});
test('storage failure is not reported as a saved successful update',async()=>{const c=setup();c.fetch=async()=>({ok:true,json:async()=>({rates:{USD:.125,CNY:1,JPY:20}})});c.saveS=()=>false;await c.refreshPrices();assert.equal(c.status.s,'err');assert.match(c.status.m,/could not be saved/);});
test('unexpected render error still releases the refresh lock',async()=>{const c=setup();c.refreshAllViews=()=>{throw Error('render');};await assert.rejects(c.refreshPrices(),/render/);c.refreshAllViews=()=>{};await c.refreshPrices();assert.equal(c.status.s,'err');});
test('metal helper counts partial results and never stamps invalid quotes',async()=>{const c=setup();vm.runInContext(fn('refreshTrackedMetalPrices'),c);c.hasQuoteKey=()=>true;c.metalQuoteToAssetPerGram=x=>x;c.recordPhysicalValuation=()=>{};c.physicalMetalValueRaw=()=>10;c.today=()=> '2026-09-07';c.S.physicalAssets=['A','B'].map(apiSymbol=>({category:'metal',priceTracking:'custom',apiSymbol,cur:'USD'}));c.fetchTwelveDataPrice=async s=>s==='A'?20:0;const result={total:0,ok:0};assert.equal(await c.refreshTrackedMetalPrices(result,()=>true),false);assert.equal(result.ok,1);assert.equal(result.total,2);assert.equal(c.S.physicalAssets[1].marketQuoteUpdatedAt,undefined);});
